(function(){'use strict';var base=new URL('.',document.currentScript.src);var current=null;
var conversations={arrival:[['茉莉','期待',0,'隆都，到你家啦！刚进门就闻到饭菜的香味了。'],['隆都','热情',1,'欢迎来我家，茉莉！今天想带你尝尝我们熟悉的高棉味道。'],['茉莉','好奇',2,'我平时也喜欢米饭配菜，不过今天这些菜，我还认不全呢。'],['隆都','介绍',3,'有鱼肉阿莫克、杂菜汤，还有几道想介绍给你的菜。'],['茉莉','开心',2,'听起来好丰富！那我今天就跟着你认识它们啦。'],['隆都','笑着',1,'先看看菜单吧，待会儿我们边吃边聊！']],after:[['茉莉','感慨',4,'隆都，这顿饭让我认识的，可不只是几个菜名。'],['隆都','好奇',3,'那你印象最深的是什么呀，茉莉？'],['茉莉','认真',0,'是鱼和米饭。原来这里的河湖、稻田，和餐桌上的食物联系得这么紧。'],['隆都','温柔',1,'是呀，对我来说，它们也是很熟悉的家的味道。'],['茉莉','回想',4,'遇到不熟悉的味道，先了解它的做法，比急着下判断更有意思。'],['隆都','开心',5,'谢谢你愿意了解！我也想听听你家乡的饭菜有什么故事。'],['茉莉','邀请',6,'下次来我家吧！换我请你吃饭，也讲讲我熟悉的味道。'],['隆都','期待',7,'说定了！下一顿饭，就跟着茉莉认识你的家乡。']]};
var coords=[[110,238],[744,365],[110,502],[744,650],[110,796],[744,944],[110,1092],[744,1219]];
function shell(title,sub){if(current)current.remove();current=document.createElement('section');current.id='story-overlay';current.setAttribute('role','dialog');current.setAttribute('aria-label',title);var panel=document.createElement('div');panel.className='story-panel';var header=document.createElement('header');header.className='story-heading';var small=document.createElement('small');small.textContent=sub;var h=document.createElement('h2');h.textContent=title;header.append(small,h);panel.append(header);current.append(panel);document.body.append(current);return panel;}
function chat(kind,done){var rows=conversations[kind],panel=shell(kind==='after'?'一顿饭之后':'今天吃什么？','茉莉 × 隆都');var log=document.createElement('div');log.className='story-log';log.setAttribute('aria-live','polite');var progress=document.createElement('div');progress.className='story-progress';var next=document.createElement('button');next.className='story-next';next.type='button';panel.append(log,progress,next);var n=0;
function advance(){if(n===rows.length){current.remove();current=null;done();return;}var row=rows[n],msg=document.createElement('div');msg.className='story-message'+(row[0]==='隆都'?' right':'');var face=document.createElement('div');face.className='story-face';face.setAttribute('role','img');face.setAttribute('aria-label',row[0]+'，'+row[1]);var c=coords[row[2]];face.style.backgroundPosition=(-c[0]*56/180)+'px '+(-c[1]*56/180)+'px';var bubble=document.createElement('div');bubble.className='story-bubble';var name=document.createElement('div');name.className='story-name';name.textContent=row[0];var emotion=document.createElement('span');emotion.className='story-emotion';emotion.textContent=row[1];name.append(emotion);var p=document.createElement('p');p.textContent=row[3];bubble.append(name,p);msg.append(face,bubble);log.append(msg);n++;progress.textContent=n+' / '+rows.length+' · 点击按钮继续对话';next.textContent=n===rows.length?(kind==='after'?'返回首页':'查看菜单'):'继续';requestAnimationFrame(function(){log.scrollTop=log.scrollHeight;});}
next.onclick=advance;advance();next.focus();}
function walk(done){var panel=shell('一起去隆都家','茉莉 × 隆都');var video=document.createElement('video');video.className='story-video';video.muted=true;video.defaultMuted=true;video.volume=0;video.autoplay=true;video.playsInline=true;video.setAttribute('muted','');video.setAttribute('playsinline','');video.disablePictureInPicture=true;video.controls=false;video.src=new URL('story-assets/walk.mp4?v=silent-2',base).href;var play=document.createElement('button');play.className='story-play';play.textContent='播放走路视频';play.hidden=true;panel.append(video,play);var finished=false;video.onended=function(){if(finished)return;finished=true;chat('arrival',done);};video.onvolumechange=function(){if(!video.muted||video.volume!==0){video.muted=true;video.volume=0;}};function begin(){video.muted=true;video.play().then(function(){play.hidden=true;}).catch(function(){play.hidden=false;});}play.onclick=begin;video.onerror=function(){play.hidden=false;play.textContent='重新加载视频';play.onclick=function(){video.load();begin();};};begin();}
window.H5Story={walk:walk,chat:chat};})();
